### ISSUE TITLE
If resume attached, parsed info from resume overwrites applicant info

### ISSUE THREAD

**Issue by huntermetts** [bullhorn/career-portal#303] opened 2020-02-07 15:42 UTC
When making a post from the career portal if the applicant applying attaches a resume, the info from the resume overwrites the fields that the applicant filled out.

For example, if I were to apply and manually put that my first name was "Hunter", but my first name on my resume was "XYZ", then in the candidate record my first name would show as "XYZ" and so on for other fields.

The resume attachment works awesome, just wondering if there's a way to turn off the overriding of information.

**Comment by pbearne** [comment] 2020-02-07 23:26
@huntermetts If you find that can't we do the opposite (we move the CV value to secondary value and use the form as primary) in matador jobs WordPress Plugin

**Comment by huntermetts** [comment] 2020-02-10 13:27
@pbearne Hello! Are you suggesting I should look into using the wordpress plugin, or that I should use that as a reference to solve this problem?

**Comment by pbearne** [comment] 2020-02-10 16:13
@huntermetts Yes, I am suggesting that you do look at the Matador Jobs Plugin I believe is an upgrade from OSCP and does solve your problem
full disclosure: I am one of the creators of MatadorJobs 
reach out for a demo :-)

**Comment by charlesabarnes** [comment] 2020-02-14 16:19
So I have looked into this, and currently, this is working as intended. I have taken steps to ensure this has been documented as a feature request, and since this is behavior within the core functionality of the public API I will be closing this issue.

I will update this issue as I see updates, but it's not guaranteed to be addressed any time soon.

**Comment by charlesabarnes** [comment] 2020-02-14 16:19
Please let me know if you have any more questions

**Closed** 2020-02-14 16:19 UTC
