### ISSUE TITLE
Applicants receive a 400 "Invalid File Extension" error when using a supported file type

### ISSUE THREAD

**Issue by kbushkoBH** [bullhorn/career-portal#45] opened 2016-03-24 21:05 UTC
In specific environments only, applicants are seeing "There was an error when applying. Try again." In IE11 dev tools, the POST call to create the candidate is returning a 400 error with the message "Invalid file extension," even though the call includes an extension listed in acceptedResumeTypes.
## Current behavior
- In the local client environment with Windows 7, IE11, end users are consistently seeing 400 errors using file extensions that should be supported. We are not able to reproduce these errors when accessing their portal outside their office, but their users say they can at home.
- I am able to reproduce this same behavior at http://careerportal-qa.bullhornstaffing.com:
- Request URL: http://public-rest-qa.bullhornstaffing.com:[port]/rest-services/[token]/apply/128347/raw?externalID=Resume&type=Resume&firstName=tomato&lastName=parrot&email=tomato%40parrot.com&phone=&format=doc
  Request Method:POST
- Response: {
  "errorCode" : 400,
  "errorMessage" : "Invalid file extension!"
  }
- This error occurs in this portal on my Win7 workstation using IE11 and any supported file type designated among acceptedResumeTypes.
## Expected behavior
- When clicking "Send" we expect the POST call to successfully create a candidate when a resume file of the correct type and size is used:
- Request URL:https://public-rest2.bullhornstaffing.com/rest-services/[token]/apply/3085/raw?externalID=Resume&type=Resume&firstName=pineapple&lastName=coconut&email=pineapple%40coconut.com&phone=&format=txt
  Request Method:POST
- Response: {
  "candidateAlreadyExisted" : false,
  "jobSubmission" : {
    "id" : 10716,
    "status" : "New Lead"
  },
  "jobOrder" : {
    "id" : 3085,
    "title" : "Silvio's Archive Test Job"
  },
  "candidate" : {
    "id" : 71010,
    "firstName" : "pineapple",
    "lastName" : "coconut",
    "phone" : null,
    "email" : "pineapple@coconut.com"
  }
  }
## Steps to replicate behavior
1. Access my BH workstation, navigate to http://careerportal-qa.bullhornstaffing.com in IE11, apply to any job with any supported resume type. 
## Screenshots

**Current (in IE11)**
Error displayed in IE:
![errorapplying](https://cloud.githubusercontent.com/assets/18052144/14030896/0dcf1e76-f1d8-11e5-9eb0-f2e3e1f1c48c.PNG)

**Expected (in Chrome)**
Same job/portal/resume file in Chrome:
![chrome1](https://cloud.githubusercontent.com/assets/18052144/14030900/13885710-f1d8-11e5-90f0-96643714ba1a.PNG)
Successful apply:
![chrome2](https://cloud.githubusercontent.com/assets/18052144/14030901/16cca9c6-f1d8-11e5-9368-dbd5803ad01d.PNG)

**Comment by jeremy-dobler** [comment] 2016-03-24 21:36
The issue is how IE passes the fileName to our REST call. IE passes the absolute file path and file name. e.g. "C:/Some/Path/To/File/filename.doc"

On the other hand Chrome passes just the fileName, e.g. "filename.doc"

Our backend service checks that the fileName does not contain certain characters as this can cause issues when we save/load the resume. The disallowed characters include the following    /  :  *  ?  <  >

We would either need to change the Request Payload for the filename via the client or after parsing the request in the backend

**Comment by jeremy-dobler** [comment] 2016-03-29 21:50
After investigation, we cannot fix this on the client side (career-portal). This requires the bug to be fixed in our backend public REST API. 

Bug has been reported on Edge as well as IE. This issue will be prioritized and fixed accordingly.

**Closed** 2016-12-19 21:25 UTC
Labels: state: implemented
